version: '3.8'

services:
  be_mc_postgres: # Needs updating
    image: postgres:16-alpine
    container_name: be_mc_postgres # Needs updating
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - '5433:5432'
    volumes:
      - be_mc_postgres_data:/var/lib/postgresql/data # Needs updating

  be_mc_redis: # Needs updating
    image: redis:alpine
    container_name: be_mc_redis # Needs updating
    ports:
      - '6379:6379'
    volumes:
      - be_mc_redis_data:/data # Needs updating

networks:
  default:
    name: nestjs_starter # Needs updating

volumes:
  be_mc_postgres_data: # Needs updating
  be_mc_redis_data: # Needs updating

