services:
  - type: web
    name: be-mc-api
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    preDeployCommand: npx prisma migrate deploy
    startCommand: pnpm start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: be-mc-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: be-mc-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: be-mc-redis
          property: port
      - key: REDIS_USERNAME
        value: ''
      - key: REDIS_PASSWORD
        value: ''
      - key: CORS_ORIGINS
        sync: false

  - type: keyvalue
    name: be-mc-redis
    plan: free
    region: frankfurt
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: be-mc-db
    plan: free
    region: frankfurt
    databaseName: be_mc
    user: be_mc
