name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Apply database migrations
        run: pnpx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Install Railway CLI
        run: pnpm add --global @railway/cli
      - name: Deploy to Railway
        run: railway up --service="be-mc"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
